/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.UserDao;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.*;
import model.User;
import java.util.*;

/**
 *
 * @author djlap
 */
public class AddUser extends javax.swing.JFrame {

    int checkusername;
    String emailPat = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    String phonpat = "^[0-9]*$";

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        userTxt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dobDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        userNameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 152, 28));

        userTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select user typ--", "Admin", "Pharmacist" }));
        getContentPane().add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 235, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 152, 34));
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 235, 38));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date Of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 152, 28));

        dobDate.setDateFormatString("dd-mm-yyyy");
        getContentPane().add(dobDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 235, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telephone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 152, 28));
        getContentPane().add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 235, 35));
        getContentPane().add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 235, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 235, 40));
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 235, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 187, 33));
        getContentPane().add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, 38));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("User Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 152, 28));
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 235, 38));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 152, 28));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        userNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameTxtKeyReleased(evt);
            }
        });
        getContentPane().add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 235, 38));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("User Add");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void userNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTxtKeyReleased
        // TODO add your handling code here:
        String username = userNameTxt.getText();
        if (!username.equals("")) {
            iconLabel.setVisible(true);
            iconLabel.setIcon(new ImageIcon("src\\images\\yes.png"));
            iconLabel.setText("");
            checkusername = 0;
            User user = new User();
            user.setUsername(userNameTxt.getText());
            UserDao dao = new UserDao();
            int counter = dao.userNameCheck(user);
            if (counter >= 1) {
                iconLabel.setIcon(new ImageIcon("src\\images\\no.png"));
                checkusername = 1;
            }

        }
    }//GEN-LAST:event_userNameTxtKeyReleased

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy");
        Date date=dobDate.getDate();
        String dob="";
        if(date!= null){
            dob=dateFormat.format(dobDate.getDate());
        }
        
        if (nameTxt.getText().trim().isEmpty() || dob.equals(null)
                || phoneTxt.getText().trim().isEmpty() || emailTxt.getText().trim().isEmpty()
                || addressTxt.getText().trim().isEmpty() || userNameTxt.getText().trim().isEmpty()||userTxt.getSelectedItem().equals("---Select user typ--") ){
            JOptionPane.showMessageDialog(this, "Plz fill all data!!", "all data error", JOptionPane.WARNING_MESSAGE);
        } 
        else {
            if (!emailTxt.getText().matches(emailPat)) {
                JOptionPane.showMessageDialog(this, "Email is not valid", "email error", JOptionPane.WARNING_MESSAGE);
            } else {
                if (checkusername == 1) {
                    JOptionPane.showMessageDialog(this, "User name alredy exits ", "user name error", JOptionPane.WARNING_MESSAGE);
                } else {

                    if (!phoneTxt.getText().matches(phonpat)) {
                        JOptionPane.showMessageDialog(this, "your phone is not valid ", "phone error", JOptionPane.WARNING_MESSAGE);
                    }else if(phoneTxt.getText().length()!=10 ||!phoneTxt.getText().substring(0,2).equals("07")){
                        JOptionPane.showMessageDialog(this, "phone number muster start with 07 and mustbe 10");
                    }
                    else {
                        if(passwordTxt.getText().length()>=8 && passwordTxt.getText().length()<=18){

                        User user = new User();
                        user.setUserRore(userTxt.getSelectedItem().toString());
                        user.setName(nameTxt.getText());
                        user.setDob(dob);
                        user.setPhone(phoneTxt.getText());
                        user.setEmail(emailTxt.getText());
                        user.setUsername(userNameTxt.getText());
                        user.setPassword(passwordTxt.getText());
                        user.setAddress(addressTxt.getText());
                        UserDao dao = new UserDao();
                        int counter = dao.newUser(user);
                        if (counter >= 1) {
                            JOptionPane.showMessageDialog(this, "USER SAVED SUCESS");
                            nameTxt.setText(null);
                            emailTxt.setText(null);
                            phoneTxt.setText(null);
                            userNameTxt.setText(null);
                            passwordTxt.setText(null);
                            addressTxt.setText(null);
                            dobDate.setDate(null);
                            userTxt.setSelectedIndex(0);
                        } else {
                            JOptionPane.showMessageDialog(this, "USER NOT SAVED");
                        }

                    }else{
                            JOptionPane.showMessageDialog(this, "Password Must be between 8 and 16","password length error",JOptionPane.WARNING_MESSAGE);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private com.toedter.calendar.JDateChooser dobDate;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JComboBox<String> userTxt;
    // End of variables declaration//GEN-END:variables
}
