/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author djlap
 */
public class PharmacistDashboard extends javax.swing.JFrame {
String username;
    /**
     * Creates new form PharmacistDashboard
     */
    public PharmacistDashboard() {
        initComponents();
    }
    public PharmacistDashboard(String tempUsername) {
        initComponents();
        username=tempUsername;
        userLabel.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMedecineBtn = new javax.swing.JButton();
        sellMedecineBtn = new javax.swing.JButton();
        viewMedecineBtn = new javax.swing.JButton();
        viewBillBtn = new javax.swing.JButton();
        updateMedecineBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        updateUserBtn1 = new javax.swing.JButton();
        exitBtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addMedecineBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addMedecineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addMedicine.png"))); // NOI18N
        addMedecineBtn.setText("Add Medecine");
        addMedecineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedecineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addMedecineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 98, 400, -1));

        sellMedecineBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sellMedecineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sellMedicine.png"))); // NOI18N
        sellMedecineBtn.setText("Sell Medecine");
        sellMedecineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellMedecineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sellMedecineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 98, 400, -1));

        viewMedecineBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewMedecineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewUser.png"))); // NOI18N
        viewMedecineBtn.setText("Vew Medecine");
        viewMedecineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedecineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewMedecineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 232, 400, -1));

        viewBillBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewBillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewBill.png"))); // NOI18N
        viewBillBtn.setText("Vew Bill");
        viewBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBillBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewBillBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 232, 400, -1));

        updateMedecineBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateMedecineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateUser.png"))); // NOI18N
        updateMedecineBtn.setText("Update Medecine");
        updateMedecineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMedecineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateMedecineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 383, 400, -1));

        profileBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        profileBtn.setText("Profiles");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        getContentPane().add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 383, 400, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pharmacist Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 6, 587, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, 1354, 10));

        updateUserBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateUserBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        updateUserBtn1.setText("Log Out");
        updateUserBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(updateUserBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 603, 269, -1));

        exitBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitBtn1.setText("Exit");
        exitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 603, 296, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 60, 40));

        userLabel.setBackground(new java.awt.Color(255, 255, 255));
        userLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 150, 40));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMedecineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedecineBtnActionPerformed
        // TODO add your handling code here:
       AddMedecine addmed=new AddMedecine();
       addmed.setVisible(true);
    }//GEN-LAST:event_addMedecineBtnActionPerformed

    private void viewMedecineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedecineBtnActionPerformed
        // TODO add your handling code here:
        ViewMedecine medview=new ViewMedecine();
        medview.setVisible(true);
                
       
    }//GEN-LAST:event_viewMedecineBtnActionPerformed

    private void viewBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBillBtnActionPerformed
        // TODO add your handling code here:
      bill bl=new bill();
      bl.setVisible(true);
    }//GEN-LAST:event_viewBillBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        UserProfilePharmacist profile=new UserProfilePharmacist(username);
        profile.setVisible(true);
        
    }//GEN-LAST:event_profileBtnActionPerformed

    private void exitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtn1ActionPerformed
        // TODO add your handling code here:
        int choice=JOptionPane.showConfirmDialog(null, "Do you want to Close application", "select",JOptionPane.YES_NO_OPTION);
        if(choice==0){
            this.dispose();
        }
    }//GEN-LAST:event_exitBtn1ActionPerformed

    private void updateUserBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
      LoginView login=new LoginView();
      login.setVisible(true);
    }//GEN-LAST:event_updateUserBtn1ActionPerformed

    private void sellMedecineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellMedecineBtnActionPerformed
        // TODO add your handling code here:
        SellMedecine sell=new SellMedecine(username);
        sell.setVisible(true);
    }//GEN-LAST:event_sellMedecineBtnActionPerformed

    private void updateMedecineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMedecineBtnActionPerformed
        // TODO add your handling code here:
        UpdateMedecine medup= new UpdateMedecine();
        medup.setVisible(true);
        
    }//GEN-LAST:event_updateMedecineBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacistDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacistDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedecineBtn;
    private javax.swing.JButton exitBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton sellMedecineBtn;
    private javax.swing.JButton updateMedecineBtn;
    private javax.swing.JButton updateUserBtn1;
    private javax.swing.JLabel userLabel;
    private javax.swing.JButton viewBillBtn;
    private javax.swing.JButton viewMedecineBtn;
    // End of variables declaration//GEN-END:variables
}
