/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import dao.BillsLocation;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.Date;

/**
 *
 * @author djlap
 */
public class SellMedecine extends javax.swing.JFrame {

    static String db_url = "jdbc:mysql://localhost:3306/Pharmacy_Managment_system";
    static String db_user = "root";
    static String db_pwd = "";
    String username;
    String numpat = "^[0-9]*$";
    int finalTotalprice = 0;
    int i;
    String billid = "";

    /**
     * Creates new form SellMedecine
     */
    public SellMedecine() {
        initComponents();
    }

    public SellMedecine(String tempusername) {
        initComponents();
        username = tempusername;
    }

    public void searchMed(String medidorname) {
        try {
            DefaultTableModel tbm = (DefaultTableModel) medTable.getModel();
            tbm.setRowCount(0);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(db_url, db_user, db_pwd);
            Statement st = con.createStatement();
            ResultSet rst = st.executeQuery("select * from medecine where name like '" + medidorname + "%' or medId like '" + medidorname + "%'");
            while (rst.next()) {
                tbm.addRow(new Object[]{rst.getString("medId") + "_ " + rst.getString("name")});

            }

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    public void clearMedFild() {
        medIdTxt.setText(null);
        nameTxt.setText(null);
        companyTxt.setText(null);
        priceTxt.setText(null);
        unitTxt.setText(null);
        totoPriceTxt.setText(null);
    }

    private String getMedId(String Prifix) {
        return Prifix + System.nanoTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        medTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        medIdTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        companyTxt = new javax.swing.JTextField();
        totoPriceTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        unitTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addToCarBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        finalTotolabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Sell Medecine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, 1354, 14));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1325, 6, 35, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 79, -1, -1));

        searchTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });
        getContentPane().add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 107, 300, 32));

        medTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine"
            }
        ));
        medTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(medTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 151, 300, 451));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mediceine ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 79, -1, -1));

        medIdTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        medIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medIdTxtActionPerformed(evt);
            }
        });
        getContentPane().add(medIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 102, 299, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 139, -1, -1));

        nameTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 162, 299, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Company Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 205, -1, -1));

        companyTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        companyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyTxtActionPerformed(evt);
            }
        });
        getContentPane().add(companyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 228, 299, -1));

        totoPriceTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totoPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totoPriceTxtActionPerformed(evt);
            }
        });
        getContentPane().add(totoPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 238, 299, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Total Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 215, -1, -1));

        unitTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitTxtActionPerformed(evt);
            }
        });
        unitTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitTxtKeyReleased(evt);
            }
        });
        getContentPane().add(unitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 172, 299, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("number Of units");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 149, -1, -1));

        priceTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtActionPerformed(evt);
            }
        });
        getContentPane().add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 112, 299, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Price Per Unit");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 89, -1, -1));

        addToCarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addToCarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        addToCarBtn.setText("Add To Cart");
        addToCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addToCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1149, 275, -1, -1));

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medecine Id", "Name", "Company Name", "Price Per Unit", "No Of Units", "Total Price"
            }
        ));
        displayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(displayTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 320, 753, 282));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("RS:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 656, -1, -1));

        finalTotolabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        finalTotolabel.setText("00");
        getContentPane().add(finalTotolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 656, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        jButton3.setText("Purches & Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1073, 643, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void medIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medIdTxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void companyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyTxtActionPerformed

    private void totoPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totoPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totoPriceTxtActionPerformed

    private void unitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitTxtActionPerformed

    private void priceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        searchMed("");
        medIdTxt.setEditable(false);
        nameTxt.setEditable(false);
        companyTxt.setEditable(false);
        priceTxt.setEditable(false);
        totoPriceTxt.setEditable(false);

    }//GEN-LAST:event_formComponentShown

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        // TODO add your handling code here:
        String search = searchTxt.getText();
        searchMed(search);
    }//GEN-LAST:event_searchTxtKeyReleased

    private void medTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medTableMouseClicked
        // TODO add your handling code here:
        int index = medTable.getSelectedRow();
        TableModel tbm = medTable.getModel();
        String nameAndId = tbm.getValueAt(index, 0).toString();
        String medid[] = nameAndId.split("_", 0);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(db_url, db_user, db_pwd);
            Statement st = con.createStatement();
            ResultSet rst = st.executeQuery("select * from medecine where medId='" + medid[0] + "'");
            while (rst.next()) {
                medIdTxt.setText(medid[0]);
                nameTxt.setText(rst.getString("name"));
                companyTxt.setText(rst.getString("company"));
                priceTxt.setText(rst.getString("price"));
                unitTxt.setText(null);
                totoPriceTxt.setText(null);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_medTableMouseClicked

    private void unitTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitTxtKeyReleased
        // TODO add your handling code here:
        if (!unitTxt.getText().equals("")) {
            if (!unitTxt.getText().matches(numpat)) {
                JOptionPane.showMessageDialog(this, "Unit is not valid");
            }
            int totoprice = Integer.parseInt(unitTxt.getText()) * Integer.parseInt(priceTxt.getText());
            totoPriceTxt.setText(String.valueOf(totoprice));
        } else {
            totoPriceTxt.setText("");
        }
    }//GEN-LAST:event_unitTxtKeyReleased

    private void addToCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCarBtnActionPerformed
        String id = medIdTxt.getText();
        String noofunit = unitTxt.getText();
        if (!noofunit.equals("") && !id.equals("")) {
            String name = nameTxt.getText();
            String companyName = companyTxt.getText();
            String pricePerUnit = priceTxt.getText();
            String totalPrice = totoPriceTxt.getText();
            int checkStock = 0;
            int checkMenInCatTable = 0;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(db_url, db_user, db_pwd);
                PreparedStatement pst = con.prepareStatement("select * from medecine where medId=?");
                //ResultSet rst = st.executeQuery("select * from medecine where medId='" + medIdTxt.getText() + "");
                pst.setString(1, id);
                ResultSet rst = pst.executeQuery();
                while (rst.next()) {
                    if (rst.getInt("quantity") >= Integer.parseInt(noofunit)) {
                        checkStock = 1;
                    } else {
                        JOptionPane.showMessageDialog(this, "medicine is out of ourstok. only" + rst.getInt("quantity") + " is left", "higy quantity error", JOptionPane.WARNING_MESSAGE);
                    }

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                if (checkStock == 1) {
                    DefaultTableModel dtbm = (DefaultTableModel) displayTable.getModel();
                    if (displayTable.getRowCount() != 0) {
                        for (i = 0; i < displayTable.getRowCount(); i++) {
                            if (dtbm.getValueAt(i, 0).equals(id)) {
                                checkMenInCatTable = 1;
                                JOptionPane.showMessageDialog(this, "medecine alredy in cart ");
                            }
                        }
                    }
                    if (checkMenInCatTable == 0) {
                        dtbm.addRow(new Object[]{
                            medIdTxt.getText(),
                            name,
                            companyName,
                            pricePerUnit,
                            unitTxt.getText(),
                            totalPrice

                        });
                        finalTotalprice = finalTotalprice + Integer.parseInt(totalPrice);
                        finalTotolabel.setText(String.valueOf(finalTotalprice));
                        JOptionPane.showMessageDialog(this, "added success");
                    }
                    clearMedFild();
                }
            } catch (Exception ex) {
                ex.printStackTrace();

            }

        } else {
            JOptionPane.showMessageDialog(this, "plz fill all data");
        }

    }//GEN-LAST:event_addToCarBtnActionPerformed

    private void displayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayTableMouseClicked
        // TODO add your handling code here:
        int index = displayTable.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(this, "Do you want to remove this Medicine", "select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = displayTable.getModel();
            String total = model.getValueAt(index, 5).toString();
            finalTotalprice = finalTotalprice - Integer.parseInt(total);
            finalTotolabel.setText(String.valueOf(finalTotalprice));
            ((DefaultTableModel) displayTable.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_displayTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (finalTotalprice != 0) {
            billid = getMedId("Bill-");
            DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
            if (displayTable.getRowCount() != 0) {
                for (int j = 0; j < displayTable.getRowCount(); j++) {
                    try {
                        Connection con = DriverManager.getConnection(db_url, db_user, db_pwd);
                        Statement st = con.createStatement();
                        st.executeUpdate("update medecine set quantity=quantity - " + Integer.parseInt(dtm.getValueAt(j, 4).toString()) + "  where medId ='" + dtm.getValueAt(j, 0) + "'");
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
            try {
                SimpleDateFormat myformat = new SimpleDateFormat("dd-MM-yyyy");
                Calendar cal = Calendar.getInstance();
                Connection con = DriverManager.getConnection(db_url, db_user, db_pwd);
                PreparedStatement ps = con.prepareStatement("insert into bill(billId,billDate,totalPaid,generatedBy) values(?,?,?,?)");
                ps.setString(1, billid);
                ps.setString(2, myformat.format(cal.getTime()));
                ps.setInt(3, finalTotalprice);
                ps.setString(4, username);
                ps.executeUpdate();
            } catch (Exception e) {
                e.printStackTrace();
            }
            //Create Bill
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try {
                PdfWriter.getInstance(doc, new FileOutputStream(BillsLocation.billpath + "" + billid + ".pdf"));
                doc.open();
                Paragraph pharmacyName = new Paragraph("                                      Lapaix Pharmacy Management System\n");
                doc.add(pharmacyName);
                Paragraph starLine = new Paragraph("**********************************************************************************");
                doc.add(starLine);
                Paragraph details = new Paragraph("\tBill ID: " + billid + "\nDate: " + new Date() + "\nTotal paid:" + finalTotalprice);
                doc.add(details);
                doc.add(starLine);
                PdfPTable tb1 = new PdfPTable(6);
                tb1.addCell("Medecine Id");
                tb1.addCell("Name");
                tb1.addCell("Compony Name");
                tb1.addCell("Price per unit");
                tb1.addCell("No of Units");
                tb1.addCell("Sub Total Price");
                for (i = 0; i < displayTable.getRowCount(); i++) {
                    String a = displayTable.getValueAt(i, 0).toString();
                    String b = displayTable.getValueAt(i, 1).toString();
                    String c = displayTable.getValueAt(i, 2).toString();
                    String d = displayTable.getValueAt(i, 3).toString();
                    String e = displayTable.getValueAt(i, 4).toString();
                    String f = displayTable.getValueAt(i, 5).toString();
                    tb1.addCell(a);
                    tb1.addCell(b);
                    tb1.addCell(c);
                    tb1.addCell(d);
                    tb1.addCell(e);
                    tb1.addCell(f);

                }
                doc.add(tb1);
                doc.add(starLine);
                Paragraph thankMsg = new Paragraph("Thonk you, Plz Visit lapaix pharm again");
                doc.add(thankMsg);
                Paragraph signature= new  Paragraph("Signature & Stamp");
                doc.add(signature);

            } catch (Exception e) {
                e.printStackTrace();
            }
            doc.close();
            String filePath = BillsLocation.billpath + billid + ".pdf";
            File file = new File(filePath);

            if (file.exists()) {
                try {
                    Desktop.getDesktop().open(file);
                } catch (IOException e) {
                    e.printStackTrace();
                }

            }
//            OpenPdf.openById(billid);
            setVisible(false);
            new SellMedecine(username).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "plz add same medecine to cart");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMedecine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMedecine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMedecine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMedecine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMedecine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCarBtn;
    private javax.swing.JTextField companyTxt;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel finalTotolabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField medIdTxt;
    private javax.swing.JTable medTable;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField totoPriceTxt;
    private javax.swing.JTextField unitTxt;
    // End of variables declaration//GEN-END:variables
}
