/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MedecineDao;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Medecine;

/**
 *
 * @author djlap
 */
public class UpdateMedecine extends javax.swing.JFrame {

    public String numberPattern = "^[0-9]*$";
    String id = "";

    /**
     * Creates new form UpdateMedecine
     */
    public UpdateMedecine() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        company = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addquantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        manfDate = new com.toedter.calendar.JDateChooser();
        expDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 10, 320, 34));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, 959, 10));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Medecine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 78, -1, 36));
        getContentPane().add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 78, 265, 36));

        searchBtn.setBackground(new java.awt.Color(204, 204, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 78, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 120, 575, 12));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 138, 138, 28));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 172, 298, 36));
        getContentPane().add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 254, 298, 38));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel4.setText("Company Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 214, 250, 28));
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 365, 298, 37));

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 310, 146, 37));
        getContentPane().add(addquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 435, 89, 37));

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel6.setText("Add Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 431, -1, 37));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 172, 298, 36));

        jLabel7.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel7.setText("Price per Unit");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 138, 298, 28));

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel8.setText("Manfacter Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 222, 298, 28));
        getContentPane().add(manfDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 268, 298, 38));
        getContentPane().add(expDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 370, 298, 38));

        jLabel9.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel9.setText("Expired Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 324, 298, 28));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 426, 155, 46));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        int checkMed = 0;
        if (searchTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Medecine id is required !!!.");
        } else {
            SimpleDateFormat dFormat = new SimpleDateFormat("mm-dd-yyyy");
            try {

                Medecine med = new Medecine();
                med.setId(searchTxt.getText());
                MedecineDao dao = new MedecineDao();
                ResultSet rst = dao.searchMedecine(med);
                while (rst.next()) {
                    searchTxt.setEditable(false);
                    id = rst.getString(2);
                    name.setText(rst.getString(3));
                    company.setText(rst.getString(4));
                    quantity.setText(rst.getString(5));
                    quantity.setEditable(false);
                    price.setText(rst.getString(6));
                    String md = rst.getString(7);
                    String xd = rst.getString(8);
                    if (md != "" && xd != null) {
                        try {
                            manfDate.setDate(dFormat.parse(md));
                            expDate.setDate(dFormat.parse(xd));
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                    checkMed = 1;
                }
                if (checkMed == 0) {
                    JOptionPane.showMessageDialog(this, "medecine not found!!");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int total = 0;
        if (addquantity.getText().equals("")) {
            total = Integer.parseInt(quantity.getText());
        } else {
            total = Integer.parseInt(addquantity.getText()) + Integer.parseInt(quantity.getText());
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy");
        Date expdate = expDate.getDate();
        Date manfdate = manfDate.getDate();
        String expd = "", manfd = "";
        if (expdate != null) {
            expd = dateFormat.format(expDate.getDate());
        }
        if (manfdate != null) {
            manfd = dateFormat.format(manfDate.getDate());
        }
        if (expd.equals(null) || manfd.equals("") || name.getText().trim().isEmpty() || company.getText().trim().isEmpty() || price.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "PLZ FILL ALL DATA", "DATA WORNING", JOptionPane.WARNING_MESSAGE);
        } else {
            Medecine med=new Medecine();
            med.setId(searchTxt.getText());
            med.setNames(name.getText());
            med.setCompany(company.getText());
            med.setQuantity(String.valueOf(total));
            med.setPrice(price.getText());
            med.setMandate(manfd);
            med.setExpdate(expd);
            MedecineDao dao=new MedecineDao();
            int counter= dao.updateMedecine(med);
            if(counter>=1){
                JOptionPane.showMessageDialog(this,"Medecine updated");
            }else{
               JOptionPane.showMessageDialog(this,"Medecine not updated","update error",JOptionPane.ERROR_MESSAGE); 
            }
                    
            

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMedecine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMedecine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMedecine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMedecine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMedecine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addquantity;
    private javax.swing.JTextField company;
    private com.toedter.calendar.JDateChooser expDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser manfDate;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
